"""add IL6 column to immuno

Revision ID: 931afd0a0213
Revises: 9ec62176f562
Create Date: 2025-04-19 18:54:02.993955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931afd0a0213'
down_revision: Union[str, None] = '9ec62176f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immuno', sa.Column('IL6', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immuno', 'IL6')
    # ### end Alembic commands ###
