"""Dodanie tabeli immuno

Revision ID: 9ec62176f562
Revises: 
Create Date: 2025-04-14 01:12:09.046368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec62176f562'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immuno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=True),
    sa.Column('CRP', sa.Float(), nullable=True),
    sa.Column('IL1', sa.Float(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immuno')
    # ### end Alembic commands ###
